### PR TITLE
Fixed thread-safety issue in C4Indexer

### LINKED ISSUE #90: Multithreaded exception when indexing views
See https://github.com/couchbase/couchbase-lite-android/issues/909#issuecomment-229565872 . @hideki wrote:

----

#### Condition that causes ForestDB error -39
- Thread-1: keep adding document into forestdb.
- Thread-2: keep run query

#### Where error -39 is thrown from
```
06-29 22:21:03.483 1804-1822/? E/CBFOREST: Forestdb Handle is being used by another thread (-39)
06-29 22:21:03.483 1804-1822/? W/CBFOREST: android stack dump
06-29 22:21:03.497 1804-1822/? W/CBFOREST: 000: 0x0xa28bc3ba dump_stack()
06-29 22:21:03.498 1804-1822/? W/CBFOREST: 001: 0x0xa28bc534 cbforest::error::_throw(fdb_status)
06-29 22:21:03.498 1804-1822/? W/CBFOREST: 002: 0x0xa28cf8e0 
06-29 22:21:03.499 1804-1822/? W/CBFOREST: 003: 0x0xa28cf992 cbforest::KeyStore::lastSequence() const
06-29 22:21:03.499 1804-1822/? W/CBFOREST: 004: 0x0xa28d9408 cbforest::MapReduceIndexer::startingSequence()
06-29 22:21:03.499 1804-1822/? W/CBFOREST: 005: 0x0xa28ed190 c4indexer_enumerateDocuments
06-29 22:21:03.499 1804-1822/? W/CBFOREST: 006: 0x0xa28f5874 Java_com_couchbase_cbforest_Indexer_iterateDocuments
06-29 22:21:03.499 1804-1822/? W/CBFOREST: android stack dump done
```

https://github.com/couchbaselabs/cbforest/blob/d6d38d9f4d98f97f7d57a7a3f3dcdcd440bc566d/CBForest/MapReduceIndex.cc#L390
```c++
    sequence MapReduceIndexer::startingSequence() {
        _latestDbSequence = _writers[0]->index->sourceStore().lastSequence();
        ...
        ...
    }
```

#### Analysis
- To insert document, `add(...)` method calls `beginTransaction()` and `endTransaction()`. In cbforest level, `beginTransaction()` and `endTransaction()`, forestdb is protected by `_transactionMutex`.
- `C4Indexer` parameter of `c4indexer_enumerateDocuments(C4Indexer *indexer, C4Error *outError)` is protected by `view->_mutex.lock();`. But it does not protect forestdb instance.

### PR DESCRIPTION
**Pull request by snej**
The underlying MapReduceIndexer calls into the source database (to get
the purge count and the last sequence) but didn't lock the C4Database
while doing so.

Fixes #90 (speculative)

### CODE REVIEW

**Comment by snej** [comment]
@hideki, could you please test with this patch and see if it fixes the error?

**Comment by hideki** [comment]
With this fix, I don't see `-39` error anymore.

However, I observe following crash in `fdb_iterator_next`.
```
07-01 15:45:08.070 173-173/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-01 15:45:08.070 173-173/? I/DEBUG: Build fingerprint: 'generic/vbox86p/vbox86p:4.4.4/KTU84P/eng.genymotion.20160609.162149:userdebug/test-keys'
07-01 15:45:08.070 173-173/? I/DEBUG: Revision: '0'
07-01 15:45:08.070 173-173/? I/DEBUG: pid: 25290, tid: 25887, name: Thread-130  >>> com.couchbase.lite.test <<<
07-01 15:45:08.070 173-173/? I/DEBUG: signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
07-01 15:45:08.402 173-173/? I/DEBUG:     eax 00000000  ebx 00000000  ecx 00000002  edx 00000000
07-01 15:45:08.402 173-173/? I/DEBUG:     esi 00011000  edi 00000000
07-01 15:45:08.402 173-173/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
07-01 15:45:08.402 173-173/? I/DEBUG:     eip 946651b8  ebp 93670a14  esp 936706fc  flags 00010246
07-01 15:45:08.402 173-173/? E/Corkscrew: unrecognized dwarf lower part encoding: 0x3f
07-01 15:45:08.402 173-173/? I/DEBUG: backtrace:
07-01 15:45:08.402 173-173/? I/DEBUG:     #00  pc 0011f1b8  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:     #01  pc 0011ad5a  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so (fdb_iterator_next+170)
07-01 15:45:08.402 173-173/? I/DEBUG:     #02  pc 0014a350  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so (cbforest::DocEnumerator::next()+272)
07-01 15:45:08.402 173-173/? I/DEBUG: stack:
07-01 15:45:08.402 173-173/? I/DEBUG:          936706bc  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          936706c0  b9824978  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936706c4  b9893dd8  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936706c8  94621501  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so (btreeblk_end+97)
07-01 15:45:08.402 173-173/? I/DEBUG:          936706cc  b9893dd8  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936706d0  b989a490  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936706d4  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          936706d8  b982497c  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936706dc  948aa3d0  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:          936706e0  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          936706e4  b9866888  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936706e8  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          936706ec  b9893dc0  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936706f0  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          936706f4  948aa3d0  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:          936706f8  94665135  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:     #00  936706fc  b9893dc0  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          93670700  b9960108  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          93670704  b9824978  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          93670708  b982497c  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          9367070c  b7678f79  /system/lib/libc.so (pthread_mutex_unlock+25)
07-01 15:45:08.402 173-173/? I/DEBUG:          93670710  93670858  [stack:25887]
07-01 15:45:08.402 173-173/? I/DEBUG:          93670714  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          93670718  40330000  
07-01 15:45:08.402 173-173/? I/DEBUG:          9367071c  948aa3d0  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:          93670720  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          93670724  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          93670728  948a8c40  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:          9367072c  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          93670730  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          93670734  948b9350  
07-01 15:45:08.402 173-173/? I/DEBUG:          93670738  948aa3d0  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:          ........  ........
07-01 15:45:08.402 173-173/? I/DEBUG:     #01  936707bc  b9824930  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936707c0  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          936707c4  00000001  
07-01 15:45:08.402 173-173/? I/DEBUG:          936707c8  00000001  
07-01 15:45:08.402 173-173/? I/DEBUG:          936707cc  b4e9dcb4  /system/lib/libdvm.so
07-01 15:45:08.402 173-173/? I/DEBUG:          936707d0  b4e9dcb4  /system/lib/libdvm.so
07-01 15:45:08.402 173-173/? I/DEBUG:          936707d4  b4f11c80  
07-01 15:45:08.402 173-173/? I/DEBUG:          936707d8  a50cced8  /dev/ashmem/dalvik-heap (deleted)
07-01 15:45:08.402 173-173/? I/DEBUG:          936707dc  00000001  
07-01 15:45:08.402 173-173/? I/DEBUG:          936707e0  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          936707e4  948aa3d0  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:          936707e8  00000000  
07-01 15:45:08.402 173-173/? I/DEBUG:          936707ec  b9824930  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936707f0  b984177c  [heap]
07-01 15:45:08.402 173-173/? I/DEBUG:          936707f4  948aa3d0  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so
07-01 15:45:08.402 173-173/? I/DEBUG:          936707f8  94690351  /data/app-lib/com.couchbase.lite.test-1/libCouchbaseLiteJavaForestDB.so (cbforest::DocEnumerator::next()+273)
07-01 15:45:08.558 25275-25275/? D/AndroidRuntime: Shutting down VM
07-01 15:45:08.558 616-25913/system_process W/ActivityManager: Error in app com.couchbase.lite.test running instrumentation ComponentInfo{com.couchbase.lite.test/android.test.InstrumentationTestRunner}:
07-01 15:45:08.558 616-25913/system_process W/ActivityManager:   Native crash
07-01 15:45:08.558 616-25913/system_process W/ActivityManager:   Native crash: Segmentation fault
```

**Comment by hideki** [comment]
Test case:
https://gist.github.com/hideki/2684dc9f589893d4ac8bea42e3940f25

If I reduce each iteration to 500, above crash does not occur.

**Comment by hideki** [comment]
According to @hisundar, crash is caused by not handling `FDB_RESULT_HANDLE_BUSY` return value from previous `fdb_iterator_next()`. And this indicates CBL Android still accessing same forestdb instance from multiple threads.

**Comment by snej** [comment]
What's being logged before the crash? If a ForestDB error is detected, a warning will be logged.

The ForestDB iterator calls are checked for errors. A handle-busy error would throw an exception.

**Comment by hideki** [comment]
I don't see any forestdb warning error message. From log, crash happens druing inserting `DocID-623`
```
07-01 17:13:00.930 4117-4700/? V/CBLite: ---> Added: {docID-00000614 #1-fe198fd1558e2bf7b7e6afdc05db8b51 @614} as seq 614
07-01 17:13:00.930 4117-4700/? V/Database: PUT _id=docID-00000615, _rev=null (allowConflict=false)
07-01 17:13:00.930 4117-4700/? V/CBLite: ---> Added: {docID-00000615 #1-14ff63e041a05eb50e0045638d07ebe8 @615} as seq 615
07-01 17:13:00.930 4117-4700/? V/Database: PUT _id=docID-00000616, _rev=null (allowConflict=false)
07-01 17:13:00.934 4117-4700/? V/CBLite: ---> Added: {docID-00000616 #1-7fb5874c2f364518eb2f2702a550de4e @616} as seq 616
07-01 17:13:00.934 4117-4700/? V/Database: PUT _id=docID-00000617, _rev=null (allowConflict=false)
07-01 17:13:00.934 4117-4700/? V/CBLite: ---> Added: {docID-00000617 #1-2e899c9996a39eb45ba3031daf985590 @617} as seq 617
07-01 17:13:00.934 4117-4700/? V/Database: PUT _id=docID-00000618, _rev=null (allowConflict=false)
07-01 17:13:00.934 173-173/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-01 17:13:00.934 173-173/? I/DEBUG: Build fingerprint: 'generic/vbox86p/vbox86p:4.4.4/KTU84P/eng.genymotion.20160609.162149:userdebug/test-keys'
07-01 17:13:00.934 173-173/? I/DEBUG: Revision: '0'
07-01 17:13:00.934 173-173/? I/DEBUG: pid: 4117, tid: 4701, name: Thread-160  >>> com.couchbase.lite.test <<<
07-01 17:13:00.934 173-173/? I/DEBUG: signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
07-01 17:13:00.934 4117-4700/? V/CBLite: ---> Added: {docID-00000618 #1-ca031cd37c5874cc51f8032a8ea2821e @618} as seq 618
07-01 17:13:00.934 4117-4700/? V/Database: PUT _id=docID-00000619, _rev=null (allowConflict=false)
07-01 17:13:00.934 4117-4700/? V/CBLite: ---> Added: {docID-00000619 #1-c697d2ab0202973d4eadac3739cde5fa @619} as seq 619
07-01 17:13:00.934 4117-4700/? V/Database: PUT _id=docID-00000620, _rev=null (allowConflict=false)
07-01 17:13:00.938 4117-4700/? V/CBLite: ---> Added: {docID-00000620 #1-918f79d62c7ab1c62b32c24824d27f74 @620} as seq 620
07-01 17:13:00.938 4117-4700/? V/Database: PUT _id=docID-00000621, _rev=null (allowConflict=false)
07-01 17:13:00.938 4117-4700/? V/CBLite: ---> Added: {docID-00000621 #1-db002cf2551f491f095b1dd685caa294 @621} as seq 621
07-01 17:13:00.938 4117-4700/? V/Database: PUT _id=docID-00000622, _rev=null (allowConflict=false)
07-01 17:13:00.938 4117-4700/? V/CBLite: ---> Added: {docID-00000622 #1-7c83040b93b196e5840df714901fd252 @622} as seq 622
07-01 17:13:00.938 4117-4700/? V/Database: PUT _id=docID-00000623, _rev=null (allowConflict=false)
07-01 17:13:01.122 173-173/? I/DEBUG:     eax 00000000  ebx 00000000  ecx 00000002  edx 00000000
07-01 17:13:01.122 173-173/? I/DEBUG:     esi 0000b000  edi 00000000
07-01 17:13:01.122 173-173/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
07-01 17:13:01.122 173-173/? I/DEBUG:     eip 946651b8  ebp 93670a14  esp 936706fc  flags 00010246
07-01 17:13:01.122 173-173/? E/Corkscrew: unrecognized dwarf lower part encoding: 0x3f
07-01 17:13:01.122 173-173/? I/DEBUG: backtrace:
07-01 17:13:01.122 173-173/? I/DEBUG:     #00  pc 0011f1b8  /data/app-lib/com.couchbase.lite.test-2/libCouchbaseLiteJavaForestDB.so
07-01 17:13:01.122 173-173/? I/DEBUG:     #01  pc 0011ad5a  /data/app-lib/com.couchbase.lite.test-2/libCouchbaseLiteJavaForestDB.so (fdb_iterator_next+170)
07-01 17:13:01.122 173-173/? I/DEBUG:     #02  pc 0014a350  /data/app-lib/com.couchbase.lite.test-2/libCouchbaseLiteJavaForestDB.so (cbforest::DocEnumerator::next()+272)
```

**Comment by snej** [comment]
I wrote a C++ test case using the C API that runs multiple threads: one adds documents, one updates the index, one queries the index. I ran it with up to 10,000 docs and didn't get any errors.

**Comment by hideki** [comment]
@snej Thank you for fixing the multi-threading issue.

**Pull request merged**
